language: python

python:
- '3.5'
- '3.6'

install:
- pip install --upgrade pip
- pip install .[test]

script: pytest

notifications:
  slack:
    rooms:
    - lcmap:UTqlh9PfPVomfpli10WKyZoh#cicd

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASS
  on:
    distributions: sdist bdist_wheel
    repo: USGS-EROS/lcmap-pyccd
    branch: master
